/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico.view;

import org.jfree.chart.*;
import java.io.BufferedReader;
import java.io.FileReader;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.title.TextTitle;

import java.awt.BasicStroke;
import java.awt.Color;

import java.awt.Font;

import com.mycompany.grafico.Index;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author meumacbook
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        radio_Titulo = new javax.swing.JRadioButton();
        radio_Legenda = new javax.swing.JRadioButton();
        radio_TituloDosEixos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radio_RotuloDeDadosPercent = new javax.swing.JRadioButton();
        radio_RotuloDeDadosValor = new javax.swing.JRadioButton();
        radio_RotuloDeDadosValorPercent = new javax.swing.JRadioButton();
        radio_CorDasBarras = new javax.swing.JRadioButton();
        radio_CorDasBarrasPorGrupo = new javax.swing.JRadioButton();
        radio_Grade = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        GraficosPadrao = new javax.swing.JComboBox<>();
        jButton_Desfazer = new javax.swing.JButton();
        jButton_RestaurarPadrao = new javax.swing.JButton();
        jButton_Fechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radio_Titulo.setText("Título");

        radio_Legenda.setText("Legenda");

        radio_TituloDosEixos.setText("Título dos eixos");
        radio_TituloDosEixos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_TituloDosEixosActionPerformed(evt);
            }
        });

        jLabel1.setText("Elementos Gráficos");

        radio_RotuloDeDadosPercent.setText("Rótulo de Dados (%)");
        radio_RotuloDeDadosPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_RotuloDeDadosPercentActionPerformed(evt);
            }
        });

        radio_RotuloDeDadosValor.setText("Rótulo de Dados - Valor");

        radio_RotuloDeDadosValorPercent.setText("Rótulo de Dados - Valor (%)");
        radio_RotuloDeDadosValorPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_RotuloDeDadosValorPercentActionPerformed(evt);
            }
        });

        radio_CorDasBarras.setText("Cor das Barras");
        radio_CorDasBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_CorDasBarrasActionPerformed(evt);
            }
        });

        radio_CorDasBarrasPorGrupo.setText("Cor das Barras (por grupos)");
        radio_CorDasBarrasPorGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_CorDasBarrasPorGrupoActionPerformed(evt);
            }
        });

        radio_Grade.setText("Grade");
        radio_Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_GradeActionPerformed(evt);
            }
        });

        jLabel2.setText("Gráficos padrão :");

        GraficosPadrao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barras Horizontais", "Barras Verticais" }));

        jButton_Desfazer.setText("Desfazer");

        jButton_RestaurarPadrao.setText("Restaurar padrão");

        jButton_Fechar.setText("Fechar");

        index = new Index();
        chart = index.start();

        jPanel2.add(chart);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_Grade)
                    .addComponent(radio_CorDasBarrasPorGrupo)
                    .addComponent(radio_CorDasBarras)
                    .addComponent(radio_RotuloDeDadosValorPercent)
                    .addComponent(radio_RotuloDeDadosValor)
                    .addComponent(radio_RotuloDeDadosPercent)
                    .addComponent(jLabel1)
                    .addComponent(radio_Legenda)
                    .addComponent(radio_Titulo)
                    .addComponent(radio_TituloDosEixos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Desfazer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_RestaurarPadrao)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Fechar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GraficosPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GraficosPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(radio_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_Legenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_TituloDosEixos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_RotuloDeDadosPercent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_RotuloDeDadosValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_RotuloDeDadosValorPercent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_CorDasBarras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_CorDasBarrasPorGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_Grade))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Desfazer)
                    .addComponent(jButton_RestaurarPadrao)
                    .addComponent(jButton_Fechar))
                .addGap(55, 55, 55))
        );

        GraficosPadrao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barras Horizontais", "Barras Verticais" }));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_TituloDosEixosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_TituloDosEixosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_TituloDosEixosActionPerformed

    private void radio_RotuloDeDadosValorPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_RotuloDeDadosValorPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_RotuloDeDadosValorPercentActionPerformed

    private void radio_CorDasBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_CorDasBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_CorDasBarrasActionPerformed

    private void radio_CorDasBarrasPorGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_CorDasBarrasPorGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_CorDasBarrasPorGrupoActionPerformed

    private void radio_GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_GradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_GradeActionPerformed

    private void radio_RotuloDeDadosPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_RotuloDeDadosPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_RotuloDeDadosPercentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    public JRadioButton getRadio_Titulo() {
        return radio_Titulo;
    }
    
    public JRadioButton getRadio_Legenda() {
        return radio_Legenda;
    }
    
    public JRadioButton getRadio_TituloDosEixos() {
        return radio_TituloDosEixos;
    }
    
    public JRadioButton getRadio_RotuloDeDadosPercent() {
        return radio_RotuloDeDadosPercent;
    }
    
    public JRadioButton getRadio_RotuloDeDadosValor() {
        return radio_RotuloDeDadosValor;
    }

    public JRadioButton getRadio_RotuloDeDadosValorPercent() {
        return radio_RotuloDeDadosValorPercent;
    }    

    public JRadioButton getRadio_CorDasBarras() {
        return radio_CorDasBarras;
    }   
    
    public JRadioButton getRadio_CorDasBarrasPorGrupo() {
        return radio_CorDasBarrasPorGrupo;
    }    

    public JRadioButton getRadio_Grade() {
        return radio_Grade;
    }    
    
    public JComboBox<String> getGraficosPadrao() {
        return GraficosPadrao;
    }
    
    public JButton getDesfazer() {
        return jButton_Desfazer;
    }
    
    public JButton getFechar() {
        return jButton_Fechar;
    }
    
    public JButton getRestaurarPadrao() {
        return jButton_RestaurarPadrao;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GraficosPadrao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton_Desfazer;
    private javax.swing.JButton jButton_Fechar;
    private javax.swing.JButton jButton_RestaurarPadrao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Index index;
    private ChartFrame chart;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radio_CorDasBarras;
    private javax.swing.JRadioButton radio_CorDasBarrasPorGrupo;
    private javax.swing.JRadioButton radio_Grade;
    private javax.swing.JRadioButton radio_Legenda;
    private javax.swing.JRadioButton radio_RotuloDeDadosPercent;
    private javax.swing.JRadioButton radio_RotuloDeDadosValor;
    private javax.swing.JRadioButton radio_RotuloDeDadosValorPercent;
    private javax.swing.JRadioButton radio_Titulo;
    private javax.swing.JRadioButton radio_TituloDosEixos;
    // End of variables declaration//GEN-END:variables
}
